### ISSUE TITLE
Adjust directory exported objects as per golint requirements

### ISSUE THREAD

**Issue by forstmeier** [heupr/core#44]
#### Overview
After the directories are re-ordered, several of the objects/fields/methods will need to be adjusted to be un/exported. Essentially:
- w/ `cmd/` directories (`frontend/`, `ingestor/`, `backend/`) -> non-exported
- w/o `cmd/` directories (`gateway/`, `conflation/`) -> exported (since these are called by the other groups of logic

Note that all five directories will now live directly within `pipeline/` and this is part of the broader pipeline rebuild.

#### TODO
- [ ] move `conflation/` into the `pipeline/` directory for clarity (it will be called by the logic in `backend/` but it may make more sense just to have it in the directory alongside the other pipeline components)
  - [ ] update all `import` paths as necessary to reflect the new location
- [ ] run `golint` on all project directories

#### Visual reference
![image](https://user-images.githubusercontent.com/13358530/31691274-8228d67e-b363-11e7-9933-d1c39c54a955.png)
