### ISSUE TITLE
Create predictions dump for "forward tests" for marketing material

### ISSUE THREAD

**Issue by forstmeier** [heupr/core#45]
#### Resources
Here are two resources for how this would theoretically look:

- the actual [probability table](https://heupr.slack.com/files/U1RHY05RB/F7LH5HGRG/this_is_code_a_wrote_to_dump_out_the_probability_table_for_each_prediction___it_shows_the_words_and_the_rank_of_those_words_relative_to_each_dev_.go) function
- how it would be [implemented](https://heupr.slack.com/files/U1RHY05RB/F7NVANGMV/-.go) in the code

#### TODO
- [x] create probability generation
  - [x] output results to file/issue
- [x] call during prediction
  - [x] collect statistics for open/unassigned issues (as if in production)
  - [x] call in `initialize.go`
  - [x] call "open" get methods
    - [x] loop over open `Issues` slice
    - [x] iterate call predict
- [x] expand "get" methods for the `gateway/`
  - [x] create helper method (content of the methods)
    - [x] update unit test
      - [x] only for helper method (likely)
  - [x] pass "open"/"closed" into the helper method (from the calling parent)
  - [x] update the `cached_gateway.go` methods as well
    - [x] change file output names to reflect "open"/"closed" options
  - [x] update all instances where the "get" methods are called

#### Stuff
- One [potential structure](https://play.golang.org/p/MZ6sHp966Q) (using `append`)
- Another using [indexing](https://play.golang.org/p/1c0_66oeHX) - went with this structure for cleanliness
