### ISSUE TITLE
Add requested "triaged" label feature

### ISSUE THREAD

**Issue by forstmeier** [heupr/core#46]
### Background
The guys at Yarn requested a "triaged" label to be added to the prediction output so that they could tell which issues have been handled.

### Notes
- access to this label assignment needs to be global (every issue assigned needs it)
- the method needs access to the target repo in order to add an issue
- eventually, this may be a **variable setting** in the setup issue

### TODOs
- [x] in `pipeline/backend/assign.go` for reference
  - [x] add functionality directly into `TriageOpenIssues`
- [x] check repo labels
  - [x] for the target repository check to see if "triaged" exists as a label
  - [x] if so return GitHub Label struct
  - [x] if not return nil
- [x] apply label to issue
  - [x] accepts Issue struct as an argument
    - [x] applies label to given Issue
- [x] remove depreciated `assign.go` and `assign_test.go` files
