### ISSUE TITLE
Create multiple database interfaces for the ingestor

### ISSUE THREAD

**Issue by forstmeier** [heupr/core#47]
## Outline
Because the `DataAccess` interface has gotten fairly large, I've decided to break it up into (at least two) separate interfaces (currently just one for reading and one for writing).

[Here's a reference link](https://heupr.slack.com/files/U1Q7TUHKM/F89RKP4TY/Possible_outline_of_several__DataAccess__interface_replacements.txt)

### Design
```go
type Database struct {
    Integrations IntegrationInterface
    PullsIssues  PullsIssuesInterface
}

db.Open()
database := Database{
    Integrations: &IntegrationImpl{DB: &db},
    PullsIssues:  &PullsIssuesImpl{DB: &db},
}

integrations := database.Integrations.ReadIntegrations(repoID)
issues := database.PullsIssues.ReadIssues(repoID)
```

### TODOs
- [ ] outline possible structures of the "sub" interfaces and place results into this TODO list
- [ ] rename various methods/functions
  - [ ] unify terminology in the database methods

**Comment by forstmeier** [comment]
### Pull request completion results
			- **estimated day(s)**: %!s(int=10)
			- **actual day(s)**:    %!g(int=5)

**Comment by forstmeier** [comment]
### Pull request completion results
			- **estimated day(s)**: %!s(int=10)
			- **actual day(s)**:    %!g(int=5)

**Comment by forstmeier** [comment]
### Pull request completion results
		- **estimated day(s)**: %!s(int=10)
		- **actual day(s)**:    %!g(int=5)

**Comment by forstmeier** [comment]
### Pull request completion results
		- **estimated day(s)**: %!s(int=10)
		- **actual day(s)**:    %!g(int=5)

**Comment by forstmeier** [comment]
### Pull request completion results
		- **estimated day(s)**: 10
		- **actual day(s)**:    5

**Comment by forstmeier** [comment]
### Pull request completion results
		- **estimated day(s)**: 10
		- **actual day(s)**:    5

**Comment by forstmeier** [comment]
### Pull request completion results
	- **estimated day(s)**: 10
	- **actual day(s)**:    5

**Comment by forstmeier** [comment]
### Pull request completion results
- **estimated day(s)**: 10
- **actual day(s)**:    5

**Comment by forstmeier** [comment]
### Completion results
- **estimated day(s)**: 10
- **actual day(s)**:    5

**Comment by forstmeier** [comment]
### Completion results
- **estimated day(s)**:	10
- **actual day(s)**:	5

**Comment by forstmeier** [comment]
### Completion results
- **estimated day(s)**:	10
- **actual day(s)**:		5

**Comment by forstmeier** [comment]
### Completion results
- **estimated day(s)**: 10
- **actual day(s)**: 5

**Comment by forstmeier** [comment]
### Completion results
- Estimated day(s): **10**
- Actual day(s): **5**

**Comment by forstmeier** [comment]
### Completion results
- Estimated day(s): **10**
- Actual day(s): **5**
