### ISSUE TITLE
Rebuild frontend server handlers and input processing logic

### ISSUE THREAD

**Issue by forstmeier** [heupr/core#51]
## Description
Because we need to 1) rebuild the website and 2) support user form input the existing handlers and server logic for `frontend` will be updated. This will take the form of a few new handlers that are pretty straightforward for the static pages as well as a more involved version for the console page. In order to protect our `ingestor` database, I'll put some sort of storage (either a database or `gob` or something) to take "snapshots" of user changes when they save settings.

### Tasks
Most of the tasks to be done will revolve around building handlers and adjusting the `frontend` server and removing depreciated code; I'll probably hold off on communication between this and `ingestor`.

[This](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/) is also an important resource regarding setting up user auth access to a website. [build-web-application-with-golang](https://github.com/astaxie/build-web-application-with-golang) is also a helpful resource.

#### static handlers
These have all been combined into a single generator function which produces a `http.HandlerFunc`.
- [x] landing page
- [x] docs page
- [x] terms/privacy page
#### repos handler
- [x] if GET method received, render console page
- [x] validate body to ensure it is safe for processing
- [x] get all installations available to the [signed in user](https://github.com/google/go-github/blob/b527232f71688a60af52f516ee87de79d0c7167b/github/apps_installation.go#L58)
- [x] populate into template and render `repos.html`
- [x] `repos.html` GET method should have `action` set to point at the `consoleHandler`
- [x] create a session and store information
#### console handler
- [x] check that GET method received
- [x] validate body to ensure it is safe for processing by checking the session
GET request
- [x] retrieve repo ID passed in the GET form value (from the `repos.html` dropdown)
- [x] place repo ID value into session values
- [x] retrieve relevant `gob` file and populate information into the `console.html` template for rendering
value
#### setup handler
- [x] check to ensure received GET requrest
- [x] parse received values (identify the repo ID and buckets created/selections made)
- [x] read related `gob` file into memory and update with form values as necessary (possibly adding values as well)
#### server
- [x] include "snapshot" storage logic (`gob` or database)
#### misc
- [x] create `setup-complete.html` file and place existing code into it
  - [x] also provide the standard formatting stuff (from the other files)
- [x] `ingestor` will need to have a timer to check and consume the "snapshots" into its own database
